name: CI/CD Pipeline for E-commerce POC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Pour permettre le déclenchement manuel

jobs:
  frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
        
    - name: Clean install dependencies
      run: |
        cd frontend
        rm -f package-lock.json
        npm install --legacy-peer-deps
        npm install typescript@4.9.5 --save-dev --legacy-peer-deps
        
    - name: Install and configure ESLint
      run: |
        cd frontend
        npm install --save-dev --legacy-peer-deps \
          eslint@8.x \
          eslint-plugin-react@latest \
          eslint-plugin-react-hooks@latest \
          eslint-plugin-jsx-a11y@latest \
          @typescript-eslint/parser@5.x \
          @typescript-eslint/eslint-plugin@5.x \
          @types/react@18.x \
          typescript@4.9.5
        
    - name: Run ESLint
      run: |
        cd frontend
        npx eslint src/ --ext .js,.jsx,.ts,.tsx --max-warnings=20 --ignore-pattern "*.config.js" --ignore-pattern "e2e/*"
        
    - name: Run Jest Tests
      run: |
        cd frontend
        npm install --save-dev jest @testing-library/react @testing-library/jest-dom @testing-library/user-event jest-environment-jsdom identity-obj-proxy babel-jest
        npm run test:coverage
        
    - name: Upload Jest coverage
      uses: actions/upload-artifact@v4
      with:
        name: frontend-coverage
        path: frontend/coverage
        
    - name: Build React app
      run: |
        cd frontend
        npm run build
        
    - name: Upload frontend build
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/build

  backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    needs: frontend
    
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ecommerce
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, pdo_mysql
        tools: composer
        
    - name: Install PHP dependencies
      run: |
        cd backend
        composer install --no-dev --optimize-autoloader
        
    - name: Run database migrations
      run: |
        # Supposons que vous avez un script pour exécuter vos migrations
        cd backend
        php database/import.php schema.sql
        
    - name: Upload backend files
      uses: actions/upload-artifact@v4
      with:
        name: backend-files
        path: backend

  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    needs: backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Newman
      run: npm install -g newman
      
    - name: Run API Tests
      run: newman run tests/api/e-commerce-api.postman_collection.json --environment tests/api/environment.json
      continue-on-error: true  # Pour que le pipeline continue même si les tests échouent

  performance-tests:
    name: Run Performance Tests
    runs-on: ubuntu-latest
    needs: api-tests
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y jmeter
        
    - name: Run JMeter Tests
      run: jmeter -n -t performance_tests/performance_tests.jmx -l performance_tests/results.jtl
      continue-on-error: true  # Pour que le pipeline continue même si les tests échouent
      
    - name: View Test Results
      run: cat performance_tests/results.jtl
      
    - name: Archive performance test results
      uses: actions/upload-artifact@v4
      with:
        name: performance-test-results
        path: performance_tests/results.jtl

  package:
    name: Create Deployment Package
    runs-on: ubuntu-latest
    needs: [frontend, backend, performance-tests]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download frontend build
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: deployment/frontend
        
    - name: Download backend files
      uses: actions/download-artifact@v4
      with:
        name: backend-files
        path: deployment/backend
        
    - name: Copy configuration files
      run: |
        mkdir -p deployment
        cp -r .ebextensions deployment/
        cp -r database deployment/
        cp README.md deployment/
        
    - name: Create ZIP file
      run: |
        cd deployment
        zip -r ../ecommerce-aws-poc.zip .
        cd ..
        
    - name: Upload deployment package
      uses: actions/upload-artifact@v4
      with:
        name: ecommerce-aws-poc
        path: ecommerce-aws-poc.zip

  deploy-to-s3:
    name: Deploy to AWS S3
    needs: package
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ecommerce-aws-poc
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
      
    - name: Upload to S3
      run: |
        # Ajouter un timestamp dans le nom du fichier
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        FILENAME="ecommerce-aws-poc-${TIMESTAMP}.zip"
        
        # Renommer le fichier
        mv ecommerce-aws-poc.zip $FILENAME
        
        # Calculer et afficher le hash MD5 pour la vérification
        md5sum $FILENAME
        
        # Uploader vers S3
        aws s3 cp $FILENAME s3://${{ secrets.AWS_S3_BUCKET }}/deployments/$FILENAME
        
        # Créer une copie "latest" pour référence facile
        aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/deployments/$FILENAME s3://${{ secrets.AWS_S3_BUCKET }}/deployments/ecommerce-aws-poc-latest.zip
        
        echo "Artifact uploaded to S3: s3://${{ secrets.AWS_S3_BUCKET }}/deployments/$FILENAME"
        echo "Latest artifact available at: s3://${{ secrets.AWS_S3_BUCKET }}/deployments/ecommerce-aws-poc-latest.zip"
      
    - name: Create deployment record
      run: |
        # Enregistrer les métadonnées de déploiement
        TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        COMMIT_SHA=${{ github.sha }}
        FILENAME="ecommerce-aws-poc-$(date +%Y%m%d-%H%M%S).zip"
        
        # Créer un fichier JSON de métadonnées
        cat > deployment-metadata.json << EOF
        {
          "timestamp": "$TIMESTAMP",
          "commit": "$COMMIT_SHA",
          "filename": "$FILENAME",
          "repository": "${{ github.repository }}",
          "workflow": "${{ github.workflow }}",
          "triggered_by": "${{ github.actor }}"
        }
        EOF
        
        # Uploader les métadonnées vers S3
        aws s3 cp deployment-metadata.json s3://${{ secrets.AWS_S3_BUCKET }}/deployments/metadata/$(date +%Y%m%d-%H%M%S).json
        
        echo "Deployment metadata recorded"

  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: frontend
    
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ecommerce
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_mysql
        
    - name: Install Selenium dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip chromium-browser chromium-chromedriver

    - name: Download Selenium Server
      run: |
        wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.16.0/selenium-server-4.16.1.jar
        java -version

    - name: Start Selenium Server
      run: |
        java -jar selenium-server-4.16.1.jar standalone > selenium.log 2>&1 &
        sleep 5

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
        npm install --save-dev selenium-webdriver @types/selenium-webdriver chromedriver

    - name: Install backend dependencies
      run: |
        cd backend
        composer install --prefer-dist --no-progress

    - name: Start backend server
      run: |
        cd backend
        php -S localhost:8000 &
        sleep 5

    - name: Start frontend server
      run: |
        cd frontend
        npm start &
        sleep 10

    - name: Run Selenium Tests
      run: |
        cd frontend
        npm run test:e2e

    - name: Upload Selenium logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: selenium-logs
        path: |
          selenium.log
          frontend/e2e-results
          
    - name: Stop servers
      if: always()
      run: |
        pkill node || true
        pkill php || true
        pkill java || true 